### ISSUE TITLE
multihits$ID not present

### ISSUE THREAD

**Issue by yhwu** [esherm/intSiteUploader#3]
Also need to consider empty sites.final and allSites

**Comment by yhwu** [comment]
Error in sort(paste0(as.integer(Rle(sites$siteID, sapply(sites.final$revmap,  :
  error in evaluating the argument 'x' in selecting a method for function 'sort': Error in (function (classes, fdef, mtable)  :
  unable to find an inherited method for function ‘Rle’ for signature ‘"NULL", "list"’
Calls: paste0 -> Rle -> <Anonymous>

**Comment by esherm** [comment]
Multihit organization has been completely restructured with the addition of multihit clustering (379cbff75addc8da4a1379fc8a6913160b12e52e) - `intSiteUploader` shouldn't care about the ID column now
